# Sample configuration for teranode-p2p
p2p:
  bootstrap_addresses:
    - "/dns4/teranode-bootstrap.bsvb.tech/tcp/9901/p2p/12D3KooWESmhNAN8s6NPdGNvJH3zJ4wMKDxapXKNUe2DzkAwKYqK"
  shared_key: "285b49e6d910726a70f205086c39cbac6d8dcc47839053a21b1f614773bbc137"
  dht_protocol_id: "/teranode"
  port: 9901
  listen_addresses:
    - "127.0.0.1"
  advertise: true
  use_private_dht: true

# New configuration: specify networks to subscribe to
# The system will automatically generate all topic combinations for these networks
networks:
  - "mainnet"